### ISSUE TITLE
Getting error page. 

### ISSUE THREAD

**Issue by bparker667** [vojtasvoboda/oc-reviews-plugin#1]
Hi I have just installed your plugin and so far its seems to have installed correctly and I am able to create a review and add the component to the page correctly, however, I am getting the error page when loading the  /reviews page. 

I looked in the logs and I am getting this error exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '<', expecting function (T_FUNCTION)' in /home/account/mydomain.org/mydomain/storage/cms/cache/54/34/reviews.htm.php:4

Please advise. Thanks

**Comment by vojtasvoboda** [comment]
Can you send me your `reviews.htm` file please? It looks like some typo at this file. Thanks

**Comment by bparker667** [comment]
[default.htm.zip](https://github.com/vojtasvoboda/oc-reviews-plugin/files/667158/default.htm.zip)

There's the default.htm file. Thanks

**Comment by vojtasvoboda** [comment]
Well, it is not reviews.htm file, but default.htm file. Can you send me file reviews.htm? It is located at your theme/pages/reviews.htm maybe? Or maybe somewhere at your partials folder? It is the file where you put the review component before.

**Comment by bparker667** [comment]
Hey I took a quick look in the reviews.htm page and found the error. Somehow it looks like the review page had some random php code... anyway it's working now. Thanks for creating this plugin and your help!

**Comment by vojtasvoboda** [comment]
No problem :-) If you like my plugin, please give me some [Review](http://octobercms.com/plugin/vojtasvoboda-reviews), it helps me a lot! Thanks
