### ISSUE TITLE
Cannot update to version 1.0.6.

### ISSUE THREAD

**Issue by cregx** [vojtasvoboda/oc-reviews-plugin#12]
I'm still using version 473 of OctoberCMS and I'm using the Review plugin version 1.0.5.

Now I have seen that there is an update available to version 1.0.6.

When I try to update the plugin in the backend > System > Updates everything runs as expected at first.

A progress indicator shows that data is being downloaded. Also the message "Update successful" appears. 

Unfortunately, however, I see that when I click on "Check updates" the same update is available **over and over** again.

**Comment by vojtasvoboda** [comment]
You can try download plugin directly from GitHub (click on the green button Code and then Download ZIP). Extract to the project , logout from the backend area and then login again.

<img width="397" alt="Screenshot 2022-01-05 v 11 14 25" src="https://user-images.githubusercontent.com/374917/148200734-806fd387-b2c8-46c7-bf10-9f68ec2ac7ee.png">

**Comment by cregx** [comment]
Thank you very much for your help. The manual update **worked**. I also had to update the database on my production server, i.e. align it with the database on the development server.
