### ISSUE TITLE
Error in backend area

### ISSUE THREAD

**Issue by LevMax** [vojtasvoboda/oc-reviews-plugin#3]
Hello! When i try to create new review in /backend/vojtasvoboda/reviews/reviews/create
there is SystemException in /modules/system/traits/ViewMaker.php line 65 with message
"The partial '_field_starrating.htm' is not found.".
If i comment this lines:
      if (!File::exists($partialPath)) {
            if ($throwException) {
                throw new SystemException(Lang::get('backend::lang.partial.not_found_name', ['name' => $partialPath]));
            }
            else {
                return false;
            }
        }

than new review is opened but without stars area. System build is 365. 
Did you have such problem?
Also review is saved in DB, but not render in frontend. The piece of code is the same as plugin documentation.
Thanks for reply and mary Christmas!

**Comment by vojtasvoboda** [comment]
Hello. I'm sorry for any inconveniences. Please try to update to latest stable build 382. I've tried now with fresh October installation and everything works well.

**Comment by LevMax** [comment]
Thanks for reply, Vojta. Yes, the latest build has resolved the problem.  But this part isn't working on frontend:
[reviews]
==
{% if reviews.reviews is not empty %}
<div class="reviews">
    <h3>What our customers say about us?</h3>
    <div class="stories">
        {% component 'reviews' %}
    </div>
</div>
{% endif %}

The only way i can reach my reviews is something like:
$facade = App::make('vojtasvoboda.reviews.facade');
$this['reviews'] = $facade->getApprovedReviews();
==
{% for review in reviews %}
//review objects
{% endfor %}

**Comment by vojtasvoboda** [comment]
It's funny, when you rename component alias from `review` to `review2` it works well. I don't know why.

But you can use just `{% if reviews is not empty %}` I just updated the documentation.

**Comment by LevMax** [comment]
Thanks! Now everything works fine!

**Comment by rangrage** [comment]
Hi @vojtasvoboda, 

How can I update the partial? 

I am using a different CSS framework and when I try to create my partial reviews/default.htm the component doesn't display on the page, even if I fork the component on the page itself, it still doesn't display anything unless I use {% component 'reviews' %} then only it displays. 

Thanks for your help.

**Comment by vojtasvoboda** [comment]
Hi @rangrage, you can insert the component to the page in CMS, then hold Cmd/Ctrl and double-click to the "component" word. CMS should expand component to the editable HTML code.

**Comment by rangrage** [comment]
Hi @vojtasvoboda, I have tried this but when the code is expanded nothing shows on the front-end.

**Comment by vojtasvoboda** [comment]
Just change `{% for review in reviews.reviews %}` to `{% for review in reviews %}` in expanded code. It works on my testing site.

**Comment by rangrage** [comment]
@vojtasvoboda yup, that fixed it. Thanks :)
