### ISSUE TITLE
I can`t start a plugin

### ISSUE THREAD

**Issue by orzech76** [vojtasvoboda/oc-reviews-plugin#8]
Hello, I have a problem with start a plugin. I added a code into my post page. I only see this: [reviews]
https://diabetyk.online/blog/post/jadlospis-dla-diabetyka-jak-drogowskaz

**Comment by vojtasvoboda** [comment]
Hello @orzech76, could you please send me a screenshot from CMS?

**Comment by orzech76** [comment]
![obraz](https://user-images.githubusercontent.com/59320942/71560370-58ebc300-2a69-11ea-9ae1-3017daf3134a.png)

**Comment by vojtasvoboda** [comment]
@orzech76 Do you have some reviews inserted in Reviews module (accessible from the main menu)?

**Comment by orzech76** [comment]
I dont have any reviews. in my main menu i dont have a module reviews https://diabetyk.online

**Comment by vojtasvoboda** [comment]
@orzech76 At the screenshot you have sent, there is Reviews main menu item. So in this menu, you have to insert some reviews and then you can see it at the websites.

**Comment by orzech76** [comment]
@vojtasvoboda Thank You. I understand. But how the user may add a opinion to my site?

**Comment by vojtasvoboda** [comment]
@orzech76 This is not possible right now, but it's part of this issue https://github.com/vojtasvoboda/oc-reviews-plugin/issues/4
