### ISSUE TITLE
How do I insert data / add a review from a form?

### ISSUE THREAD

**Issue by Niklas81** [vojtasvoboda/oc-reviews-plugin#9]
Trying to insert data using a form. The following works in the sense that I can see the inserted variables after the form is submitted, but I'm getting an error upon submitting (which I cannot see with my current setup) unless I comment out the line with `$reviews->storeReview`:

```php
function test_input($data) {
    $data = trim($data);
    $data = stripslashes($data);
    $data = htmlspecialchars($data);
    return $data;
}

function onStart() {
    $reviews = App::make('vojtasvoboda.reviews.facade');
    $this["reviews"] = $reviews->getApprovedReviews();
    
    if (isset($_POST["rating"]) && $_POST["rating"] != ""){
        $rating = (int)$_POST["rating"];
        if (is_int($rating) && $rating >= 0 && $rating <= 5)
            $this["rating"] = $rating;
    }
    if (isset($_POST["name"]) && $_POST["name"] != ""){
        $this["name"] = $_POST["name"];
    }
    if (isset($_POST["title"]) && $_POST["title"] != ""){
        $this["title"] = $_POST["title"];
    }
    if (isset($_POST["content"]) && $_POST["content"] != ""){
        $this["content"] = $_POST["content"];
    }    
    if (isset($_POST["email"])){
        $email = $this->test_input($_POST["email"]);
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
          $emailErr = "Invalid email format";
        }
        if (!isset($emailErr)) $this['email'] = $email;                
    }
    if (!isset($emailErr) && isset($this["email"]) && isset($this["name"]) && isset($this["title"]) && isset($this["rating"]) && isset($this["content"])){
       $reviews->storeReview(["name" => $this["name"], "email" => $this["email"], "rating" => $this["rating"], "title" => $this["title"], "content" => $this["content"]]);
        
    }

}
```

**Comment by Niklas81** [comment]
Looking through your codebase, I find out that `approved` must be included in the $data array, and that `content` must be at least 6 characters long. Setting this in the call to `storeReview` and it works fine.
I do however think that opinionated, non-apparent design-choices should be mentioned in your Documentation/Readme, so that not every developer needs to dig through your code.

**Comment by vojtasvoboda** [comment]
Thanks, I've updated readme and add mention about validation rules: https://github.com/vojtasvoboda/oc-reviews-plugin/commit/2539a830ec011531e586d3fccaad57c590adba15

Btw you can store new review also like that:

```
function onStart() {
    $data = Input::all();
    $review = $reviews->storeReview($data);
}
```

There is [$fillable array](https://github.com/vojtasvoboda/oc-reviews-plugin/blob/master/models/Review.php#L42) for control which properties are set.

But the better approach will be by creating method onSubmit() and then call it by October AJAX framework:

```
<form data-request="onSubmit">
```

Then you can use built-in [form validation](https://octobercms.com/docs/ajax/extras#ajax-validation).
